// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeAZt26QmGQdpdqkiz876m9hC679laBDI',
    appId: '1:456723010616:android:eef0eb4e1cce2f596602cd',
    messagingSenderId: '456723010616',
    projectId: 'easylocker-b2a5f',
    storageBucket: 'easylocker-b2a5f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeAZt26QmGQdpdqkiz876m9hC679laBDI',
    appId: '1:456723010616:android:eef0eb4e1cce2f596602cd',
    messagingSenderId: '456723010616',
    projectId: 'easylocker-b2a5f',
    storageBucket: 'easylocker-b2a5f.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBHSvNFtpuxX7BVZWTFeLa5Qavh8qiCNnE',
  //   appId: '1:328543597125:ios:749bc15aea986d6909692c',
  //   messagingSenderId: '328543597125',
  //   projectId: 'localmenu-app',
  //   storageBucket: 'localmenu-app.appspot.com',
  //   iosClientId:
  //       '328543597125-1qvmf783eub634dojduuramf2bg93dm7.apps.googleusercontent.com',
  //   iosBundleId: 'com.krobot.localmenu.dev',
  // );
}
